### ISSUE TITLE
Wrong URI for CC image

### ISSUE THREAD

**Issue by 7wells** [nwtour/compare-0ad#1]
Hello nwtour!

As 0 A.D. player, I stumbled over your tool, which I very much like. Thanks for creating it! 👍 
In all html files, the URI to the image of the CC is wrong (civic center.png - should be: civic_centre.png), e.g.:

`<table><tr><td>Zivilisation</td><td><h3><img src='https://raw.githubusercontent.com/0ad/0ad/master/binaries/data/mods/public/art/textures/ui/session/portraits/structures/civic center.png' width='20' height='20'>Verwaltungssitz</h3></td></tr>`

should be this instead:

`<table><tr><td>Zivilisation</td><td><h3><img src='https://raw.githubusercontent.com/0ad/0ad/master/binaries/data/mods/public/art/textures/ui/session/portraits/structures/civic_centre.png' width='20' height='20'>Verwaltungssitz</h3></td></tr>`

I have corrected this and have the files locally on my PC. Since I have only cery very basic knowledge about GutHib, I do not know how to proceed. Shall I fork and then do a PR from that fork, or would you grant me write permission to do a PR on the branch, or how does it work? In fact, this would be the first time ever that I actively change something on GitHub, so please be patient with me. Thank you so much! 😄

PS: If you do not want to change this, that is of course also ok for me.

**Comment by nwtour** [comment]
Fixed in https://github.com/nwtour/compare-0ad/commit/8535a1b92ea207ac0d71c90da664d7de401b37de

**Comment by 7wells** [comment]
Thank you so much! :)
